#!/bin/bash

# time for each run in loop
t="01:30:00"

# command for each job to loop over with different params
cmd="./main_FS_perc"
input="input_FS_perc"
count=0

for i in `seq 1 4`
do
    for p in 0. .2 .4 .6 .8 1.0 1.2 1.4 1.6 1.8 2.
    do
        for N in 9 11 13 15 17 19 21 23
        do
            sbatch --time=$t run_MPI $cmd $input $p $N 1
            echo "sbatch --time=$t run_MPI $cmd $input $p $N 1"
            
            count=$((count+1))
        done
    
    done
done

echo "$count jobs submitted"