#!/bin/bash

# walltime requested
#SBATCH -t 6:00:00

# number of nodes and partition
#SBATCH -N 1 -p RM

# cores per node
#SBATCH --ntasks-per-node=128

# modules
module load gcc
module load openmpi/4.0.5-gcc10.2.0
module load mkl

# mpirun
mpirun -np 128 ./main_io_measurement ${1} ${2} ${3} ${4}